name: npm-run-build flow

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: npm-run-build
        run: |
          echo Hello, world!
          node -v
          npm install
          npm run build