name: npm-run-build flow

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: npm

      - name: install and build
        run: |
          echo ===== Node.jsバージョン確認 =====
          node -v
          echo ===== Install dependencies =====
          npm ci
          echo ===== npm run build =====
          npm run build
          - name: Commit and Push

      - name: git commit + git push
        run: |
          git add -N .
          if ! git diff --exit-code --quiet
          then
            git config user.name "your name"
            git config user.email "your mailaddress@yourma.com"
            git add .
            git commit -m "commit message"
            git pull
            git push origin master
          fi